# App
spring.application.name=backend-stage1

# Local PostgreSQL
#spring.profiles.active=dev

#spring.datasource.url=jdbc:postgresql://localhost:5432/hng_stage1
# Database - uses environment variables in production, falls back to local
# Database - all from environment variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Set logging levels (e.g., set your own package to DEBUG)
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Server
server.port=${PORT:8080}

