# App
spring.application.name=backend-stage1

# Local PostgreSQL
#spring.profiles.active=dev

#spring.datasource.url=jdbc:postgresql://localhost:5432/hng_stage1
# Database - uses environment variables in production, falls back to local
# Database - all from environment variables

#spring.datasource.url=${spring.datasource.urlL}
#spring.datasource.username=${spring.datasource.username}
#spring.datasource.password=${spring.datasource.password}

    #spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres?user=postgres.agcoohvmnzfcharshfrc&password=W7e+3d!ik3v$C/H
#spring.datasource.username=postgres.agcoohvmnzfcharshfrc
#spring.datasource.password=W7e+3d!ik3v$C/H

#spring.datasource.url=${spring.datasource.url}
#spring.datasource.username=${spring.datasource.username}
#spring.datasource.password=${spring.datasource.password}

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


s-1-eu-west-3.pooler.supabase.com:6543/postgres


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Set logging levels (e.g., set your own package to DEBUG)
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jackson.date-format: yyyy-MM-dd'T'HH:mm:ssZ
spring.jackson.time-zone: UTC

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# GitHub OAuth
github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}
github.redirect-uri=${GITHUB_REDIRECT-URI}

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiry={JWT_ACCESS_TOKEN_EXPIRY}
jwt.refresh-token-expiry={JWT_REFRESH_TOKEN_EXPIRY}

#jwt.access-token-expiry=180000
#jwt.refresh-token-expiry=300000

# App
app.frontend-url=${http://localhost:3000}

# Server
#server.port=${PORT:8888}


